name: Build Deb

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install-build-tools
      run: sudo apt-get -y install autoconf automake autopoint libtool g++ make
    - name: autoreconf
      run: autoreconf -vfi
    - name: configure
      run: ./configure
    - name: make
      run: make
